---
- hosts: all

  roles:
    - ubuntu

    # needs to be setup first to use npm / nvm later
    - web-server/node

    - cli/bash
    - cli/git
    - cli/make
    - cli/python

    - database/postgresql

    - web-server/nginx
    - web-server/php-fpm

    - monitortoise/deploy
    - monitortoise/nginx

    - web-server/letsencrypt
