name: Monitortoise Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: donatello
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install symfony cli
        run: |
          wget https://get.symfony.com/cli/installer -O - | bash
          mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      
      - name: Setup mailpit server
        run: |
          sudo bash < <(curl -sL https://raw.githubusercontent.com/axllent/mailpit/develop/install.sh)
          /usr/local/bin/mailpit &

      - name: Preparing .env file for github
        run: cp .env .env.local

      - name: Changing APP_ENV to test
        run: sed -i 's/APP_ENV=dev/APP_ENV=test/' .env.local

      - name: Setup project
        run: make install

      - name: Phpstan
        run: bin/phpstan --memory-limit=1G

      - name: Automatic code sniffer fixing
        run: bin/ecs --fix
        continue-on-error: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.php'
          commit_message: ":robot::art: Fix CS"

      - name: Checking code sniffer after fixes
        run: bin/ecs

      - name: Checking twig templates
        run: bin/console lint:twig templates

      - name: Run server
        run: make serve

      - name: Load data
        run: make reset-test

      - name: Unit and integration tests
        run: bin/phpunit --testdox --fail-on-warning --fail-on-risky --fail-on-incomplete --fail-on-skipped

      - name: End to end tests
        run: pnpm cypress run

      # On failure
      - name: Get failing screenshots
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: cypress-screenshots
          path: |
            cypress/screenshots
      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#ci'
          SLACK_COLOR: '#FF5555'
          SLACK_USERNAME: 'monitortoise'
          SLACK_ICON_EMOJI: ':turtle:'
          SLACK_TITLE: Last commit
          SLACK_FOOTER: "“Try not. Do or do not. There is no try.” — Yoda"